### ISSUE TITLE
support cwcwidth along wcwidth

### ISSUE THREAD

**Issue by pmp-p** [salt-die/batgrl#15]
when available 
https://pypi.org/project/cwcwidth/
should offer more performance than stock wcwidth ( and i guess it could be made to work with numpy str too https://github.com/sebastinas/cwcwidth )

```
import importlib.util
if importlib.util.find_spec('cwcwidth'):
    import cwcwidth
    def wcswidth(o):
        return cwcwidth.wcswidth(str(o))
    def wcwidth(o):
        return cwcwidth.wcwidth(str(o))
else:
    from wcwidth import wcwidth, wcswidth
```
nb: i did not test perf but i'm willing to help if there's something real to gain in generic use of batgrl.

**Comment by salt-die** [comment]
I'll take a look. I have plans to cythonize certain parts of batgrl already, so this won't even add an extra dependency!

**Comment by salt-die** [comment]
Now that Advent of Code season is over, I've been taking a look at this finally. The numpy str issue is easy to work around, we can just use `ndarray.item()` to get the python string, but a much bigger issue is different values from wcwidth on windows:
```py
>>> import cwcwidth
>>> cwcwidth.wcwidth("📄")
1
>>> cwcwidth.wcwidth("📁")
1
>>> import wcwidth
>>> wcwidth.wcwidth("📄")
2
>>> wcwidth.wcwidth("📁")
2
```
I'll think about how to continue.
