### ISSUE TITLE
App PPI

### ISSUE THREAD

**Issue by gustavoguedess** [salt-die/batgrl#16]
I need to increase my terminal's PPI when running the application. 
I would like to show 360 columns in my sparkline without grouping. But to show all columns I need to make my font smaller.
There's some method that I can change the PPI of the application?

**Comment by salt-die** [comment]
No, this isn't possible. There's no vt100 escapes that will modify the size of a character in a terminal.  Changing your font size is one solution; another is putting your sparkline into a scroll view, which is what I would recommend. If you need help just comment here, but I'm closing this issue as can't fix.
