### ISSUE TITLE
small typo in the documentation "Proper Pong Preamble"

### ISSUE THREAD

**Issue by Guillaume-Fgt** [salt-die/batgrl#17]
> Finally, add the ball to the game field.
> 
> ```
> ball = Ball(
>     left_paddle,
>     right_paddle,
>     left_score_label,
>     right_score_label,
>     size=(1, 2),
>     background_color_pair=WHITE_ON_BLUE,
> )
> 
> game_field.add_gadgets(
>     left_paddle,
>     right_paddle,
>     divider,
>     left_score_label,
>     right_score_label,
> )
> self.add_gadget(game_field)
> ```

ball is missing in the add_gadgets arguments.

I discovered your library through your visualizations for advent of code. It's really cool. I will study the code and hope to achieve my own ones soon! Thank you for sharing.

**Comment by salt-die** [comment]
Thanks for letting me know!
